#!/usr/bin/env bash
# helix-python-detect.sh — Detect the real Python binary on this machine.
# Skips Microsoft Store stubs ("Python was not found").
# Persists to ~/.claude/helix-python.conf as `export HELIX_PYTHON=<cmd>`.
set -uo pipefail

CONF="$HOME/.claude/helix-python.conf"

is_real_python() {
    local cmd="$1"
    command -v "$cmd" >/dev/null 2>&1 || return 1
    local output rc
    output=$("$cmd" --version 2>&1)
    rc=$?
    [[ $rc -eq 0 ]] || return 1
    [[ "$output" == *"was not found"* ]] && return 1
    [[ "$output" == *"Microsoft Store"* ]] && return 1
    [[ "$output" =~ ^Python\ [0-9] ]] || return 1
    return 0
}

DETECTED=""
for cmd in python3 python py; do
    if is_real_python "$cmd"; then
        DETECTED="$cmd"
        break
    fi
done

if [[ -z "$DETECTED" ]]; then
    echo "helix-python-detect: ERROR — no real Python found (tried python3, python, py)." >&2
    echo "Install Python 3.10+ or fix PATH, then re-run this script." >&2
    exit 1
fi

VERSION=$("$DETECTED" --version 2>&1 | head -1)
HOST=$(hostname 2>/dev/null || echo unknown)
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$CONF" <<EOF
# helix-python.conf — autogenerated by helix-python-detect.sh
# Generated:  $TS
# Host:       $HOST
# Detected:   $VERSION
export HELIX_PYTHON="$DETECTED"
EOF

echo "helix-python-detect: $DETECTED ($VERSION) → $CONF"
